#Hypergraph
graph_type: &g_t hypergraph
#K_neigs: [5, 15, 30, 50, 100, 200]
K_neigs: 5
m_prob: 1.0
is_probH: True

#Train
#max_epoch: [30, 80, 100, 200, 250, 500, 1000, 2000]
max_epoch: 200
#n_hid: [16, 32, 64, 100, 128, 256]
n_hid: 64
#lr: [0.001, 0.005]
lr: 0.001
milestones: [100]
gamma: 0.9
#drop_out: [0, 0.1, 0.5]
drop_out: 0
print_freq: 100
weight_decay: 0.0005
decay_step: 200
decay_rate: 0.7

#Run Level
grid_sear: False
n_splits: 5
n_repeats: 5
